from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

import numpy as np

from .common import write_json
from .frontend import EXPLICIT_TENSOR_MODE, LinearData, LinearOp
from .lowering import TILE_SIZE, TilePlanEntry, plan_linear_tiles


def _activation_matrix(spec: LinearOp) -> np.ndarray:
    if spec.activation_mode == "row_ramp":
        base = np.arange(spec.k, dtype=np.int8)
        return np.tile(base, (spec.m, 1))
    if spec.activation_mode == "column_ramp":
        base = np.arange(spec.m, dtype=np.int8).reshape(spec.m, 1)
        return np.tile(base, (1, spec.k))
    if spec.activation_mode == "identity":
        return np.eye(spec.m, spec.k, dtype=np.int8)
    raise ValueError(f"Unsupported activation_mode: {spec.activation_mode}")


def _weight_matrix(spec: LinearOp) -> np.ndarray:
    if spec.weight_mode == "constant_3":
        return np.full((spec.k, spec.n), 3, dtype=np.int8)
    if spec.weight_mode == "identity":
        return np.eye(spec.k, spec.n, dtype=np.int8)
    if spec.weight_mode == "column_ramp":
        base = np.arange(spec.n, dtype=np.int8).reshape(1, spec.n)
        return np.tile(base, (spec.k, 1))
    raise ValueError(f"Unsupported weight_mode: {spec.weight_mode}")


def _resolve_activation_matrix(spec: LinearOp, data: LinearData | None = None) -> np.ndarray:
    if spec.activation_mode in {EXPLICIT_TENSOR_MODE, "from tensor"}:
        if data is None:
            raise ValueError("activation_mode='from_tensor' requires LinearData.activations.")
        if data.activations.shape != (spec.m, spec.k):
            raise ValueError("LinearData.activations must have shape (m, k).")
        return data.activations
    return _activation_matrix(spec)


def _resolve_weight_matrix(spec: LinearOp, data: LinearData | None = None) -> np.ndarray:
    if spec.weight_mode in {EXPLICIT_TENSOR_MODE, "from tensor"}:
        if data is None:
            raise ValueError("weight_mode='from_tensor' requires LinearData.weights.")
        if data.weights.shape != (spec.k, spec.n):
            raise ValueError("LinearData.weights must have shape (k, n).")
        return data.weights
    return _weight_matrix(spec)


def _compute_product(activations: np.ndarray, weights: np.ndarray, bias: np.ndarray | None = None) -> np.ndarray:
    """Bit-accurate FP16→FP32 matmul matching NPU RTL semantics.

    Uses CUDA GPU acceleration when available (via cuda.golden_accel),
    with automatic NumPy fallback.
    """
    try:
        from npu_cuda.golden_accel import compute_golden_single
        return compute_golden_single(activations, weights, bias)
    except ImportError:
        # Cast to float16, multiply/accumulate into float32 to match RTL semantics
        product = activations.astype(np.float16) @ weights.astype(np.float16)
        product = product.astype(np.float32)
        if bias is not None:
            product = product + bias.astype(np.float32)
        return product


def _golden_outputs_from_product(product: np.ndarray, global_row_base: int, global_col_base: int) -> list[dict[str, object]]:
    outputs: list[dict[str, object]] = []
    # Cast float32 matrix directly viewing its IEEE 754 bit layout as int32
    bit_representations = product.view(np.int32).tolist()
    for row_idx, vector in enumerate(bit_representations):
        outputs.append(
            {
                "drain_addr": row_idx,
                "global_row": global_row_base + row_idx,
                "global_col_base": global_col_base,
                "vector": vector,
            }
        )
    return outputs


def _pad_matrix(matrix: np.ndarray, target_rows: int = TILE_SIZE, target_cols: int = TILE_SIZE) -> np.ndarray:
    padded = np.zeros((target_rows, target_cols), dtype=matrix.dtype)
    padded[: matrix.shape[0], : matrix.shape[1]] = matrix
    return padded


def _build_tiled_root_manifest(spec: LinearOp, plan: list[TilePlanEntry]) -> dict[str, object]:
    return {
        "manifest_version": "0.1",
        "package_id": spec.package_id,
        "op_type": "gemm_tiled",
        "description": "L6 study package generated from a tiled Linear export plan.",
        "shape": {"m": spec.m, "k": spec.k, "n": spec.n},
        "tile_size": TILE_SIZE,
        "tile_count": len(plan),
        "files": {"tiles": "tiles.json"},
        "l6_study": {
            "logical_op": "linear",
            "activation_mode": spec.activation_mode,
            "weight_mode": spec.weight_mode,
        },
    }


def _build_single_tile_manifest(spec: LinearOp) -> dict[str, object]:
    return {
        "manifest_version": "0.1",
        "package_id": spec.package_id,
        "op_type": "gemm_tile",
        "description": "L6 study package generated from a single 16x16 Linear tile.",
        "source": {
            "origin": "l6_linear_export",
            "notes": "Generated by l6_toolchain.linear_export for study and replay bring-up.",
        },
        "shape": {"m": spec.m, "k": spec.k, "n": spec.n},
        "tile": {
            "m_tile_base": 0,
            "n_tile_base": 0,
            "tile_rows": spec.m,
            "tile_cols": spec.n,
        },
        "files": {
            "activations": "activations.json",
            "weights": "weights.json",
            "golden": "golden.json",
        },
        "execution": {
            "seq_len": spec.k,
            "k_tile_count": 1,
            "require_weight_preload": True,
            "acc_clear_policy": "first_pass_overwrite",
            "drain_addresses": list(range(spec.m)),
        },
        "format": {
            "activation_layout": "row_major_16xint8_vectors",
            "weight_layout": "k_major_rows_of_16_columns",
            "golden_layout": "drain_address_to_16xint32_vector_map",
            "lane_order": "lane0_to_lowest_column_offset",
            "endianness": "little",
            "payload_encoding": "json",
        },
        "compare": {"mode": "exact", "require_exact_match": True},
        "l6_study": {
            "logical_op": "linear",
            "activation_mode": spec.activation_mode,
            "weight_mode": spec.weight_mode,
        },
    }


def _emit_tiled_tile(
    tile_dir: Path,
    tile_id: int,
    spec: LinearOp,
    tile: TilePlanEntry,
    activations: np.ndarray,
    weights: np.ndarray,
    product: np.ndarray,
) -> dict[str, object]:
    m_base = tile.m_tile_base
    n_base = tile.n_tile_base
    k_base = tile.k_tile_base
    tile_m = tile.tile_m
    tile_k = tile.tile_k
    tile_n = tile.tile_n

    activation_slice = activations[m_base : m_base + tile_m, k_base : k_base + tile_k]
    weight_slice = weights[k_base : k_base + tile_k, n_base : n_base + tile_n]
    padded_activations = _pad_matrix(activation_slice.astype(np.int8))
    padded_weights = _pad_matrix(weight_slice.astype(np.int8))

    activation_payload = {
        "layout": "row_major_16xint8_vectors",
        "valid_rows": tile_m,
        "valid_cols": tile_k,
        "rows": padded_activations.astype(int).tolist(),
    }
    weight_payload = {
        "layout": "k_major_rows_of_16_columns",
        "valid_rows": tile_k,
        "valid_cols": tile_n,
        "rows": padded_weights.astype(int).tolist(),
    }

    tile_manifest = {
        "manifest_version": "0.1",
        "package_id": f"{spec.package_id}_tile_{tile_id:03d}",
        "op_type": "gemm_tile_pass",
        "shape": {"m": spec.m, "k": spec.k, "n": spec.n},
        "tile": {
            "m_tile_base": m_base,
            "n_tile_base": n_base,
            "k_tile_base": k_base,
            "tile_rows": tile_m,
            "tile_cols": tile_n,
            "tile_depth": tile_k,
        },
        "execution": {
            "seq_len": tile_k,
            "k_pass_index": tile.k_pass_index,
            "k_tile_count": tile.k_tile_count,
            "acc_clear": tile.acc_clear,
            "emit_drain_after": tile.emit_drain_after,
        },
        "files": {
            "activations": "activations.json",
            "weights": "weights.json",
        },
    }

    write_json(tile_dir / "manifest.json", tile_manifest)
    write_json(tile_dir / "activations.json", activation_payload)
    write_json(tile_dir / "weights.json", weight_payload)

    if tile.emit_drain_after:
        tile_product = product[m_base : m_base + tile_m, n_base : n_base + tile_n]
        golden_payload = {
            "layout": "drain_address_to_16xint32_vector_map",
            "valid_rows": tile_m,
            "valid_cols": tile_n,
            "outputs": _golden_outputs_from_product(tile_product, m_base, n_base),
        }
        tile_manifest["files"]["golden"] = "golden.json"
        write_json(tile_dir / "manifest.json", tile_manifest)
        write_json(tile_dir / "golden.json", golden_payload)

    return {
        "tile_id": tile_id,
        "dir": f"tiles/tile_{tile_id:03d}",
        **asdict(tile),
    }


def export_linear_tiled_package(
    output_dir: str | Path,
    spec: LinearOp | None = None,
    data: LinearData | None = None,
    *,
    tile_order: list[TilePlanEntry] | None = None,
) -> Path:
    spec = spec or LinearOp()
    spec.validate_positive()

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    activations = _resolve_activation_matrix(spec, data)
    weights = _resolve_weight_matrix(spec, data)
    product = _compute_product(activations, weights, None if data is None else data.bias)
    plan = tile_order if tile_order is not None else plan_linear_tiles(spec)

    tiles_dir = output_path / "tiles"
    tiles_dir.mkdir(exist_ok=True)

    manifest = _build_tiled_root_manifest(spec, plan)

    tile_index: list[dict[str, object]] = []
    for tile_id, tile in enumerate(plan):
        tile_dir = tiles_dir / f"tile_{tile_id:03d}"
        tile_dir.mkdir(exist_ok=True)
        tile_index.append(_emit_tiled_tile(tile_dir, tile_id, spec, tile, activations, weights, product))

    readme = f"""# {spec.package_id}

Generated by `l6_toolchain.export_linear_tiled_package`.

- Logical op: tiled Linear
- Shape: M={spec.m}, K={spec.k}, N={spec.n}
- Tile size: 16x16x16
- Tile count: {len(plan)}

This package is intended for L6 study of tiling, tail handling, and split-K scheduling.
"""

    write_json(output_path / "manifest.json", manifest)
    write_json(output_path / "tiles.json", {"tiles": tile_index})
    (output_path / "README.md").write_text(readme, encoding="utf-8")

    return output_path


def export_linear_tile_package(
    output_dir: str | Path,
    spec: LinearOp | None = None,
    data: LinearData | None = None,
) -> Path:
    spec = spec or LinearOp()
    spec.validate()

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    activations = _resolve_activation_matrix(spec, data)
    weights = _resolve_weight_matrix(spec, data)
    golden = _golden_outputs_from_product(
        _compute_product(activations, weights, None if data is None else data.bias),
        0,
        0,
    )

    manifest = _build_single_tile_manifest(spec)

    activation_payload = {
        "layout": "row_major_16xint8_vectors",
        "rows": activations.astype(int).tolist(),
    }
    weight_payload = {
        "layout": "k_major_rows_of_16_columns",
        "rows": weights.astype(int).tolist(),
    }
    golden_payload = {
        "layout": "drain_address_to_16xint32_vector_map",
        "outputs": golden,
    }

    readme = f"""# {spec.package_id}

Generated by `l6_toolchain.linear_export`.

- Logical op: single-tile Linear
- Shape: M={spec.m}, K={spec.k}, N={spec.n}
- Activation mode: {spec.activation_mode}
- Weight mode: {spec.weight_mode}

This package is intended for L6 study before moving to arbitrary-shape tiling.
"""

    write_json(output_path / "manifest.json", manifest)
    write_json(output_path / "activations.json", activation_payload)
    write_json(output_path / "weights.json", weight_payload)
    write_json(output_path / "golden.json", golden_payload)
    (output_path / "README.md").write_text(readme, encoding="utf-8")

    return output_path


__all__ = ["export_linear_tile_package", "export_linear_tiled_package"]